apiVersion: v1
kind: ConfigMap
metadata:
  name: helptech-config
data:
  DB_PROJECT_NAME: "helptec"
  DB_HOST: "host.minikube.internal"
  DB_PORT: "3310"
  DB_NAME: "helptec"
  DB_USER: "root"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helptech-backend
spec:
  replicas: 1

  selector:
    matchLabels:
      app: helptech-backend

  template:
    metadata:
      labels:
        app: helptech-backend

    spec:
      containers:
        - name: helptech-backend
          image: higorsantanafiec/helptech-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: helptech-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: helptech-db-secret
                  key: DB_PASSWORD

            - name: APP_FIREBASE_CONFIG_FILE
              value: "/etc/firebase/serviceAccountKey.json"

          volumeMounts:
            - name: firebase-credentials
              mountPath: /etc/firebase
              readOnly: true

      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-service-account
